apiVersion: v2
type: application
appVersion: 1.0.14
description: STRG.BeHave collaborative-filtering-service
name: behave-collaborative-filtering-service
version: 0.1.4
kubeVersion: ">=1.16.0-0"
keywords:
  - behave
  - collaborative-filtering
home: https://github.com/strg-at/tree/main/charts/behave-collaborative-filtering-service
maintainers:
  - name: Nils MÃ¼ller
    email: nils.mueller@strg.at
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.3.0
